# Generated by Django 4.2.11 on 2024-04-18 20:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False, verbose_name='identificador do registro de usuário')),
                ('user_name', models.CharField(max_length=50, verbose_name='nome do usuário')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='endereço de e-mail do usuário')),
                ('password', models.CharField(max_length=50, verbose_name='senha do usuário')),
                ('is_active', models.BooleanField(default=False, verbose_name='indicativo se usuário está ativo ou não no sistema')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='data de criação do registro de usuário no sistema')),
                ('last_login', models.DateTimeField(null=True, verbose_name='data de último login do usuário no sistema')),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
