# Generated by Django 4.2.11 on 2024-04-20 14:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id_stock', models.AutoField(primary_key=True, serialize=False, verbose_name='identificador do registro de ativo')),
                ('name', models.CharField(max_length=50, verbose_name='nome do ativo')),
                ('acronym', models.CharField(max_length=10, unique=True, verbose_name='sigla do ativo')),
                ('sector', models.CharField(max_length=100, null=True, verbose_name='setor de operação do ativo')),
                ('is_brazilian', models.BooleanField(default=True, verbose_name='indicativo se ativo é brasileiro')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='data de criação do registro de ativo no sistema')),
            ],
            options={
                'db_table': 'stock',
            },
        ),
        migrations.CreateModel(
            name='UserStock',
            fields=[
                ('max_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor máximo do túnel estático definido pelo usuário')),
                ('min_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor mínimo do túnel estático definido pelo usuário')),
                ('update_frequency', models.IntegerField(max_length=20, verbose_name='frequencia em minutos de atualização dos dados do ativo definido pelo usuário')),
                ('id_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.stock')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'user_stock',
            },
        ),
        migrations.CreateModel(
            name='StockHistory',
            fields=[
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='data de criação do registro de usuário no sistema')),
                ('previous_close', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='preço do frechamento anterior')),
                ('open_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='preço de aberuta do ativo')),
                ('max_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='preço de máxima do ativo')),
                ('min_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='preço de mínima do ativo')),
                ('volume', models.BigIntegerField(default=0, verbose_name='volume do ativo')),
                ('id_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.stock')),
            ],
            options={
                'db_table': 'stock_history',
            },
        ),
    ]
