# Generated by Django 4.2.11 on 2024-04-24 00:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstock',
            name='update_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='data de criação/atualização do registro'),
        ),
        migrations.CreateModel(
            name='PriceQuoteHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_quote', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='preço da cotação no momento da monitorização')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='data de criação do registro de cotação monitorada')),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='data de atualização do registro em caso de não alteração da cotação monitorada desde último monitoramento')),
                ('update_frequency', models.IntegerField(null=True, verbose_name='frequencia em minutos de atualização dos dados da cotação')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.stock')),
            ],
            options={
                'db_table': 'price_quote_history',
            },
        ),
        migrations.AddConstraint(
            model_name='pricequotehistory',
            constraint=models.UniqueConstraint(fields=('stock', 'creation_date'), name='unique_stock_creation_date_combination'),
        ),
    ]
